apiVersion: v1
kind: Secret
metadata:
  name: market-board-secret
type: Opaque
stringData:
  MYSQL_USER: "root"
  MYSQL_PASSWORD: "yzj24243456"
  REDIS_PASSWORD: ""
  RABBITMQ_USER: "guest"
  RABBITMQ_PASSWORD: "guest"